jwt:
#  signerKey: "385e9984cbf346ccb72a61b85fbab7486f7df3f75e6c810c4cda28421d48fb21"
  #Thiết lập thời gian của JWT tùy thuộc vào hệ thống
  valid-duration: 7200 # in second
  refreshable-duration: 72000 #in second